## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := generic-gnu
ALL_TARGETS += libs

PREFIX=/home/dott/ogv.js/build/wasm-mt/root
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8dx-vp9dx-nopost-nodocs-generic-gnu-v1.8.1
else
DIST_DIR?=$(DESTDIR)/home/dott/ogv.js/build/wasm-mt/root
endif
LIBSUBDIR=lib

VERSION_STRING=v1.8.1

VERSION_MAJOR=1
VERSION_MINOR=8
VERSION_PATCH=1

CONFIGURE_ARGS=--prefix=/home/dott/ogv.js/build/wasm-mt/root --target=generic-gnu --extra-cflags=-pthread -s USE_PTHREADS=1 -I/home/dott/emsdk/upstream/emscripten/system/lib/libcxxabi/include/ --enable-multithread --enable-vp9-decoder --disable-vp8-encoder --disable-vp9-encoder --disable-shared --disable-docs --disable-examples --disable-tools --disable-unit-tests
CONFIGURE_ARGS?=--prefix=/home/dott/ogv.js/build/wasm-mt/root --target=generic-gnu --extra-cflags=-pthread -s USE_PTHREADS=1 -I/home/dott/emsdk/upstream/emscripten/system/lib/libcxxabi/include/ --enable-multithread --enable-vp9-decoder --disable-vp8-encoder --disable-vp9-encoder --disable-shared --disable-docs --disable-examples --disable-tools --disable-unit-tests
