## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
SRC_PATH="../../../libvpx"
SRC_PATH_BARE=../../../libvpx
BUILD_PFX=
TOOLCHAIN=generic-gnu
ASM_CONVERSION=../../../libvpx/build/make/ads2gas.pl
GEN_VCPROJ=
MSVS_ARCH_DIR=

CC=/home/dott/emsdk/upstream/emscripten/emcc
CXX=/home/dott/emsdk/upstream/emscripten/em++
AR=/home/dott/emsdk/upstream/emscripten/emar
LD=/home/dott/emsdk/upstream/emscripten/em++
AS=as
STRIP=./buildscripts/fake-strip.sh
NM=/home/dott/emsdk/upstream/bin/llvm-nm

CFLAGS  =  -DNDEBUG -O3 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wparentheses-equality -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wuninitialized -Wunused -Wextra -Wundef -Wframe-larger-than=52000 -Wno-unused-function -std=gnu89 -Wshorten-64-to-32 -pthread -s USE_PTHREADS=1 -I/home/dott/emsdk/upstream/emscripten/system/lib/libcxxabi/include/
CXXFLAGS  =  -DNDEBUG -O3 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wparentheses-equality -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wuninitialized -Wunused -Wextra -Wno-unused-function -std=c++11 -std=c++11 -pthread -s USE_PTHREADS=1 -I/home/dott/emsdk/upstream/emscripten/system/lib/libcxxabi/include/
ARFLAGS = -crs$(if $(quiet),,v)
LDFLAGS = -pthread
ASFLAGS = 
extralibs =  -lpthread
AS_SFX    = .S
EXE_SFX   = 
VCPROJ_SFX = 
RTCD_OPTIONS = 
LIBYUV_CXXFLAGS =  -Wno-missing-declarations -Wno-missing-prototypes -Wno-unused-parameter
fmt_deps = sed -e 's;^\([a-zA-Z0-9_]*\)\.o;${@:.d=.o} $@;'
HAVE_VPX_PORTS=yes
HAVE_PTHREAD_H=yes
HAVE_UNISTD_H=yes
CONFIG_DEPENDENCY_TRACKING=yes
CONFIG_INSTALL_BINS=yes
CONFIG_INSTALL_LIBS=yes
CONFIG_GCC=yes
CONFIG_MULTITHREAD=yes
CONFIG_VP8_DECODER=yes
CONFIG_VP9_DECODER=yes
CONFIG_VP8=yes
CONFIG_VP9=yes
CONFIG_DECODERS=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_STATIC=yes
CONFIG_OS_SUPPORT=yes
CONFIG_WEBM_IO=yes
CONFIG_LIBYUV=yes
CONFIG_TEMPORAL_DENOISING=yes
